# Generated by Django 4.0.8 on 2023-03-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='movie',
            new_name='Movie',
        ),
    ]
