# Generated by Django 4.0.8 on 2023-03-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_message_match'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
