# Generated by Django 4.0.8 on 2023-03-20 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritemovie',
            old_name='Movie',
            new_name='movie',
        ),
    ]
