# Generated by Django 4.0.8 on 2023-03-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_match_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
