# Generated by Django 4.0.8 on 2023-03-23 03:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_match_is_blocked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouritemovie',
            unique_together={('user', 'movie')},
        ),
    ]
